PREFIX cn: <http://tiny.cc/open-contracting#>
PREFIX com: <https://w3id.org/commerce#>
PREFIX dc: <http://purl.org/dc/terms/>

SELECT ?Uri ?Title ?Document
WHERE 
{ 
    ?Uri a cn:Attachment ;
           dc:title ?Title ;
           com:contentUrl  ?Document ;
           cn:contract @contract .
}